chore: fix quitting the ci test run;

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,25 +8,26 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
-    - name: Install Poetry
-      run: |
-        curl -sSL https://install.python-poetry.org | python -
-    - name: Install dependencies
-      run: |
-        poetry install
-    - name: Run Mock Server in Background
-      run: |
+      - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.x"
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python -
+      - name: Install dependencies
+        run: |
+          poetry install
+      - name: Run Mock Server in Background
+        run: |
           poetry run python tests/mock_server.py &
           echo "Mock Server PID=$!" >> $GITHUB_ENV
-    - name: Run tests with pytest
-      run: |
-        poetry run pytest tests/
-    - name: Cleanup Mock Server
-      run: |
-        kill $Mock_Server_PID
-      if: always()
+      - name: Run tests with pytest
+        run: |
+          poetry run pytest tests/
+      - name: Cleanup Mock Server
+        run: |
+          echo "Attempting to kill Mock Server at PID $Mock_Server_PID"
+          kill $Mock_Server_PID || echo "Failed to kill Mock Server. It may have already exited."
+          if: always()
